name: reservation-api

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        project: reservation-api
    container_name: reservation-api
    command: [
      make, 
      run
    ]
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
    env_file: ".env.docker"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: reservation-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

