"""new_relationship

Revision ID: c6b8a3eedae4
Revises: 92cc4760c86a
Create Date: 2025-02-07 19:20:28.941674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b8a3eedae4'
down_revision: Union[str, None] = '92cc4760c86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations_table', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reservations_table_sala_id_rooms_table'), 'reservations_table', 'rooms_table', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reservations_table_sala_id_rooms_table'), 'reservations_table', type_='foreignkey')
    op.drop_column('reservations_table', 'room_id')
    # ### end Alembic commands ###
